
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:07:09.420806' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:07:09.420806', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT (1) AS "a" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4 LIMIT 1; args=(4,)
(0.000) SELECT (1) AS "a" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4 LIMIT 1; args=(4,)
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4 LIMIT 1; args=(4,)
(0.000) BEGIN; args=None
(0.000) UPDATE "golearnApp_uteacherinfo" SET "name" = 'nnn', "upasswd" = 'nnn123', "uemail" = '33@qq.com', "ubirth" = '1997-07-08', "uimage" = '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', "umoney" = 501, "usex" = 'nan', "uGo_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', "uTeach_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', "udescripition" = '描述您的围棋教学经历', "can_createschool" = 0 WHERE "golearnApp_uteacherinfo"."id" = 4; args=('nnn', 'nnn123', '33@qq.com', '1997-07-08', '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', 501, 'nan', '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', '描述您的围棋教学经历', False, 4)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:07:09.569517' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:07:09.569517', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_ustudentinfo"."id", "golearnApp_ustudentinfo"."name", "golearnApp_ustudentinfo"."upasswd", "golearnApp_ustudentinfo"."uemail", "golearnApp_ustudentinfo"."ubirth", "golearnApp_ustudentinfo"."uimage", "golearnApp_ustudentinfo"."umoney", "golearnApp_ustudentinfo"."usex", "golearnApp_ustudentinfo"."can_upgrade" FROM "golearnApp_ustudentinfo" WHERE "golearnApp_ustudentinfo"."id" = 4; args=(4,)
(0.000) SELECT "golearnApp_ustudentinfo"."id", "golearnApp_ustudentinfo"."name", "golearnApp_ustudentinfo"."upasswd", "golearnApp_ustudentinfo"."uemail", "golearnApp_ustudentinfo"."ubirth", "golearnApp_ustudentinfo"."uimage", "golearnApp_ustudentinfo"."umoney", "golearnApp_ustudentinfo"."usex", "golearnApp_ustudentinfo"."can_upgrade" FROM "golearnApp_ustudentinfo" LIMIT 21; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:07:33.210874' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:07:33.210874', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_ustudentinfo"."id", "golearnApp_ustudentinfo"."name", "golearnApp_ustudentinfo"."upasswd", "golearnApp_ustudentinfo"."uemail", "golearnApp_ustudentinfo"."ubirth", "golearnApp_ustudentinfo"."uimage", "golearnApp_ustudentinfo"."umoney", "golearnApp_ustudentinfo"."usex", "golearnApp_ustudentinfo"."can_upgrade" FROM "golearnApp_ustudentinfo" WHERE "golearnApp_ustudentinfo"."id" = 4; args=(4,)
(0.000) SELECT "golearnApp_ustudentinfo"."id", "golearnApp_ustudentinfo"."name", "golearnApp_ustudentinfo"."upasswd", "golearnApp_ustudentinfo"."uemail", "golearnApp_ustudentinfo"."ubirth", "golearnApp_ustudentinfo"."uimage", "golearnApp_ustudentinfo"."umoney", "golearnApp_ustudentinfo"."usex", "golearnApp_ustudentinfo"."can_upgrade" FROM "golearnApp_ustudentinfo" LIMIT 21; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:07:45.573390' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:07:45.573390', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:08:25.585146' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:08:25.585146', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:11:42.250831' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:11:42.250831', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:11:44.349497' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:11:44.349497', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:11:46.229097' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:11:46.229097', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.000) BEGIN; args=None
(0.000) UPDATE "golearnApp_uteacherinfo" SET "name" = 'nnn', "upasswd" = 'nnn123', "uemail" = '33@qq.com', "ubirth" = '1997-07-08', "uimage" = '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', "umoney" = 401, "usex" = 'nan', "uGo_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', "uTeach_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', "udescripition" = '描述您的围棋教学经历', "can_createschool" = 1 WHERE "golearnApp_uteacherinfo"."id" = 4; args=('nnn', 'nnn123', '33@qq.com', '1997-07-08', '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', 401, 'nan', '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', '描述您的围棋教学经历', True, 4)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:11:46.347882' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:11:46.347882', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:11:48.449216' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:11:48.449216', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 404, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.core.urlresolvers.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLPattern None ^LearningGo/register.html>], [<RegexURLPattern None ^LearningGo/login.html>], [<RegexURLPattern None ^LearningGo/index.html>], [<RegexURLPattern None ^LearningGo/userinfo/student>], [<RegexURLPattern None ^LearningGo/userinfo/buyupgrade>], [<RegexURLPattern None ^LearningGo/userinfo/upgradeinfo>], [<RegexURLPattern None ^LearningGo/userinfo/teacher>], [<RegexURLPattern None ^LearningGo/userinfo/wallet>], [<RegexURLPattern None ^LearningGo/userinfo/buycreatecampus>], [<RegexURLPattern None ^LearningGo/userinfo/buycreateclass>], [<RegexURLPattern None ^LearningGo/userinfo/addcampus>], [<RegexURLPattern None ^LearningGo/userinfo/addclass/>]], 'path': 'LearningGo/userinfo/asscampus'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:15.657932' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:15.657932', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee8b5978>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee8b6048>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee8a0f28>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6748>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6860>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b38>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b2a20>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c35f8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6a58>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6b00>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee9b4b38>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a20>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a58>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3ac8>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c39e8>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b70>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a90>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3ba8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3c18>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b00>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3be0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee8b5978>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee8b6048>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee8a0f28>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6748>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6860>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b38>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b2a20>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c35f8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6a58>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8b6b00>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee9b4b38>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a20>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a58>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3ac8>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c39e8>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b70>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3a90>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3ba8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3c18>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3b00>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8c3be0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:18.952623' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:18.952623', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_campus"; args=()
(0.000) SELECT "golearnApp_campus"."id", "golearnApp_campus"."name", "golearnApp_campus"."abbreviation", "golearnApp_campus"."stage", "golearnApp_campus"."logo", "golearnApp_campus"."bio", "golearnApp_campus"."pupose", "golearnApp_campus"."teacher_id", "golearnApp_campus"."can_createclass" FROM "golearnApp_campus" ORDER BY "golearnApp_campus"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee8a0bf8>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:19.058619' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:19.058619', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:21.160494' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:21.160494', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee889320>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee8f2e80>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee885f28>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8816d8>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8819e8>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8ec6d8>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8e6588>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88b4a8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8820f0>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881f28>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881860>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8f27f0>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881c50>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88be80>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88be48>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bfd0>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88beb8>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881978>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bf98>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bef0>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bb00>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee889320>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee8f2e80>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee885f28>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8816d8>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8819e8>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8ec6d8>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8e6588>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88b4a8>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8820f0>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881f28>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881860>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee8f27f0>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881c50>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88be80>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88be48>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bfd0>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88beb8>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee881978>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bf98>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bef0>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee88bb00>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:23.022013' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:23.022013', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_uteacherinfo"; args=()
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" ORDER BY "golearnApp_uteacherinfo"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee8caea0>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:23.154617' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:23.154617', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:24.947582' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:24.947582', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'golearnApp' AND "django_content_type"."model" = 'uteacherinfo'); args=('golearnApp', 'uteacherinfo')
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:25.076008' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:25.076008', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:32.002599' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:32.002599', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_uteacherinfo"; args=()
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" ORDER BY "golearnApp_uteacherinfo"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee99c488>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:33.365452' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:33.365452', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 2; args=(2,)
(0.005) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'golearnApp' AND "django_content_type"."model" = 'uteacherinfo'); args=('golearnApp', 'uteacherinfo')
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:33.519575' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:33.519575', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:36.449858' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:36.449858', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_uteacherinfo"; args=()
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" ORDER BY "golearnApp_uteacherinfo"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee93fd08>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:37.905353' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:37.905353', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 1; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'golearnApp' AND "django_content_type"."model" = 'uteacherinfo'); args=('golearnApp', 'uteacherinfo')
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:14:38.027390' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:14:38.027390', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 404, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.core.urlresolvers.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLPattern None ^LearningGo/register.html>], [<RegexURLPattern None ^LearningGo/login.html>], [<RegexURLPattern None ^LearningGo/index.html>], [<RegexURLPattern None ^LearningGo/userinfo/student>], [<RegexURLPattern None ^LearningGo/userinfo/buyupgrade>], [<RegexURLPattern None ^LearningGo/userinfo/upgradeinfo>], [<RegexURLPattern None ^LearningGo/userinfo/teacher>], [<RegexURLPattern None ^LearningGo/userinfo/wallet>], [<RegexURLPattern None ^LearningGo/userinfo/buycreatecampus>], [<RegexURLPattern None ^LearningGo/userinfo/buycreateclass>], [<RegexURLPattern None ^LearningGo/userinfo/addcampus>], [<RegexURLPattern None ^LearningGo/userinfo/addclass/>]], 'path': 'LearningGo/userinfo/asscampus'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 404, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.core.urlresolvers.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLPattern None ^LearningGo/register.html>], [<RegexURLPattern None ^LearningGo/login.html>], [<RegexURLPattern None ^LearningGo/index.html>], [<RegexURLPattern None ^LearningGo/userinfo/student>], [<RegexURLPattern None ^LearningGo/userinfo/buyupgrade>], [<RegexURLPattern None ^LearningGo/userinfo/upgradeinfo>], [<RegexURLPattern None ^LearningGo/userinfo/teacher>], [<RegexURLPattern None ^LearningGo/userinfo/wallet>], [<RegexURLPattern None ^LearningGo/userinfo/buycreatecampus>], [<RegexURLPattern None ^LearningGo/userinfo/buycreateclass>], [<RegexURLPattern None ^LearningGo/userinfo/addcampus>], [<RegexURLPattern None ^LearningGo/userinfo/addclass/>]], 'path': 'LearningGo/userinfo/asscampus'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:06.139882' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:06.139882', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:08.158641' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:08.158641', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:35.660391' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:35.660391', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.000) BEGIN; args=None
(0.000) INSERT INTO "golearnApp_campus" ("name", "abbreviation", "stage", "logo", "bio", "pupose", "teacher_id", "can_createclass") VALUES ('undefined', 'xjtu', '1', '/home/loading_21th/LearningGo/static/image/undefined/weixin.png', '介绍您的学校', '描述教学宗旨', 4, 0); args=['undefined', 'xjtu', '1', '/home/loading_21th/LearningGo/static/image/undefined/weixin.png', '介绍您的学校', '描述教学宗旨', 4, False]
(0.000) BEGIN; args=None
(0.000) UPDATE "golearnApp_uteacherinfo" SET "name" = 'nnn', "upasswd" = 'nnn123', "uemail" = '33@qq.com', "ubirth" = '1997-07-08', "uimage" = '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', "umoney" = 401, "usex" = 'nan', "uGo_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', "uTeach_credential" = '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', "udescripition" = '描述您的围棋教学经历', "can_createschool" = 0 WHERE "golearnApp_uteacherinfo"."id" = 4; args=('nnn', 'nnn123', '33@qq.com', '1997-07-08', '/home/loading_21th/LearningGo/static/image/nnn/D310B351A98564BA846E9CC4BA4BF285.jpg', 401, 'nan', '/home/loading_21th/LearningGo/static/image/nnn/6632482837165689736.jpg', '/home/loading_21th/LearningGo/static/image/nnn/6632266233373897668.jpg', '描述您的围棋教学经历', False, 4)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:35.833706' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:35.833706', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" WHERE "golearnApp_uteacherinfo"."id" = 4; args=(4,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:49.684945' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:49.684945', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_uteacherinfo"; args=()
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo" ORDER BY "golearnApp_uteacherinfo"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee87a158>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:51.746668' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:51.746668', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee8c10b8>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee7b12e8>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee853d08>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b11d0>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1390>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b15f8>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1668>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1400>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1748>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b16a0>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b15c0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1630>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1588>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1438>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b14e0>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1358>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b13c8>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1908>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1898>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1320>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b18d0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f80ee8c10b8>, 'user': <SimpleLazyObject: <User: admin>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f80ee7b12e8>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee853d08>>, 'request': <WSGIRequest: GET '/admin/golearnApp/'>, 'DEFAULT_MESSAGE_LEVELS': {'INFO': 20, 'DEBUG': 10, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'has_permission': True, 'site_url': '/', 'title': 'Golearnapp administration', 'LANGUAGE_BIDI': False, 'app_label': 'golearnApp', 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4c88>, 'app_list': [{'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b11d0>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1390>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b15f8>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1668>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1400>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1748>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b16a0>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b15c0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'available_apps': [{'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efabc898>, 'has_module_perms': True, 'models': [{'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1630>, 'object_name': 'Group', 'add_url': '/admin/auth/group/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1588>, 'object_name': 'User', 'add_url': '/admin/auth/user/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/auth/'}, {'app_label': 'golearnApp', 'name': 'Golearnapp', 'has_module_perms': True, 'models': [{'admin_url': '/admin/golearnApp/campus/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1438>, 'object_name': 'Campus', 'add_url': '/admin/golearnApp/campus/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/classroom/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b14e0>, 'object_name': 'Classroom', 'add_url': '/admin/golearnApp/classroom/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/homework/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1358>, 'object_name': 'Homework', 'add_url': '/admin/golearnApp/homework/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/students_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b13c8>, 'object_name': 'Students_classes', 'add_url': '/admin/golearnApp/students_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/teacher_classes/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1908>, 'object_name': 'Teacher_classes', 'add_url': '/admin/golearnApp/teacher_classes/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/ustudentinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1898>, 'object_name': 'Ustudentinfo', 'add_url': '/admin/golearnApp/ustudentinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/uteacherinfo/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b1320>, 'object_name': 'Uteacherinfo', 'add_url': '/admin/golearnApp/uteacherinfo/add/', 'perms': {'delete': True, 'change': True, 'add': True}}, {'admin_url': '/admin/golearnApp/videos/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80ee7b18d0>, 'object_name': 'Videos', 'add_url': '/admin/golearnApp/videos/add/', 'perms': {'delete': True, 'change': True, 'add': True}}], 'app_url': '/admin/golearnApp/'}], 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7f80efab4be0>}]"
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:53.047305' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:53.047305', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "golearnApp_campus"; args=()
(0.000) SELECT "golearnApp_campus"."id", "golearnApp_campus"."name", "golearnApp_campus"."abbreviation", "golearnApp_campus"."stage", "golearnApp_campus"."logo", "golearnApp_campus"."bio", "golearnApp_campus"."pupose", "golearnApp_campus"."teacher_id", "golearnApp_campus"."can_createclass" FROM "golearnApp_campus" ORDER BY "golearnApp_campus"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in 'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in "[{'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f80ee8caea0>>, 'True': True, 'None': None, 'False': False}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in 'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
(0.002) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:53.132220' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:53.132220', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:54.381547' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:54.381547', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "golearnApp_campus"."id", "golearnApp_campus"."name", "golearnApp_campus"."abbreviation", "golearnApp_campus"."stage", "golearnApp_campus"."logo", "golearnApp_campus"."bio", "golearnApp_campus"."pupose", "golearnApp_campus"."teacher_id", "golearnApp_campus"."can_createclass" FROM "golearnApp_campus" WHERE "golearnApp_campus"."id" = 1; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'golearnApp' AND "django_content_type"."model" = 'campus'); args=('golearnApp', 'campus')
(0.000) SELECT "golearnApp_uteacherinfo"."id", "golearnApp_uteacherinfo"."name", "golearnApp_uteacherinfo"."upasswd", "golearnApp_uteacherinfo"."uemail", "golearnApp_uteacherinfo"."ubirth", "golearnApp_uteacherinfo"."uimage", "golearnApp_uteacherinfo"."umoney", "golearnApp_uteacherinfo"."usex", "golearnApp_uteacherinfo"."uGo_credential", "golearnApp_uteacherinfo"."uTeach_credential", "golearnApp_uteacherinfo"."udescripition", "golearnApp_uteacherinfo"."can_createschool" FROM "golearnApp_uteacherinfo"; args=()
Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'can_delete_related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'Context' has no attribute 'can_delete_related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'can_delete_related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [can_delete_related] in '[{\'True\': True, \'None\': None, \'False\': False}, {\'model\': \'uteacherinfo\', \'can_add_related\': True, \'change_related_template_url\': \'/admin/golearnApp/uteacherinfo/__fk__/change/\', \'url_params\': \'_to_field=id&_popup=1\', \'can_change_related\': True, \'add_related_url\': \'/admin/golearnApp/uteacherinfo/add/\', \'name\': \'teacher\', \'widget\': \'<select id="id_teacher" name="teacher">\\n<option value="">---------</option>\\n<option value="1">Uteacherinfo object</option>\\n<option value="2">Uteacherinfo object</option>\\n<option value="4" selected="selected">Uteacherinfo object</option>\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n    \'>]>}]'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2018-03-25 08:17:54.458120' AND "django_session"."session_key" = 'k91a9zwhxhaa41hwno6hh390g2a0ulac'); args=('2018-03-25 08:17:54.458120', 'k91a9zwhxhaa41hwno6hh390g2a0ulac')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
